---
title: Biodiversity comparisons across cities
pkg: rgbif
layout: usecases
---

In this example, we compare biodiversity in different regsions using GBIF data from rgbif.

This example can be done using BISON data as well with our rbison package.

```{r defaults, eval=TRUE, echo=FALSE, cache=TRUE}
opts_chunk$set(comment=NA, warning=FALSE, message=FALSE, fig.width=7, fig.height=6, fig.path="../assets/usecases-images/")
```

### Load libraries

```{r load}
library("rgbif")
library("ggplot2")
library("plyr")
library("RCurl")
```

### Get bounding boxes for some cites

```{r box}
rawdat <- getURL('https://raw.githubusercontent.com/amyxzhang/boundingbox-cities/master/boundbox.txt')
dat <- read.table(text = rawdat, header = FALSE, sep="\t", col.names=c("city","minlat","maxlon","maxlat","minlon"))
dat <- data.frame(city=dat$city, minlon=dat$minlon, minlat=dat$minlat, maxlon=dat$maxlon, maxlat=dat$maxlat)
```

```{r newsearch}
getdata <- function(x){
  coords <- as.numeric(x[c('minlon','minlat','maxlon','maxlat')])
  num <- occ_search(geometry = coords)$meta$count
  data.frame(city=x['city'], richness=num, stringsAsFactors = FALSE)
}
```

```{r}
out <- apply(dat, 1, getdata)
out <- merge(dat, ldply(out), by="city") # merge to original table
# add centroids from bounding boxes
out <- transform(out, lat = (minlat+maxlat)/2, lon = (minlon+maxlon)/2)
```

### Plot data

```{r plot}
mapp <- map_data('world')
ggplot(mapp, aes(long, lat)) +
  geom_polygon(aes(group=group), fill="white", alpha=0, color="gray80", size=0.8) +
  geom_point(data=out, aes(lon, lat, color=richness), size=5, alpha=0.8) +
  scale_color_gradient2(low = "white", high = "steelblue") +
  labs(x="", y="") +
  theme_grey(base_size=14) +
  theme(legend.position = "bottom", legend.key = element_blank())
```

### Notes

Bounding lat/long data from [here](https://raw.github.com/amyxzhang/boundingbox-cities/master/boundbox.txt)
